install:
- npm install # команда установки зависимостей
build: off
build_script:
- npm run build # команда сборки
test_script:
- npm run lint && npm test # скрипт тестирования
deploy_script: # скрипт развёртывания
- git config --global credential.helper store
- git config --global user.name AppVeyor
- git config --global user.email ci@appveyor.com
- echo "https://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:buzh61@github.com" > "$HOME/.git-credentials"
- npx push-dir --dir=dist --branch=gh-pages --force --verbose
